# Generated by Django 2.2 on 2020-04-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdesigning',
            name='image',
        ),
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='experience',
            name='todate',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='machinelearning',
            name='todate',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='softwaredevelopment',
            name='todate',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='webdesigning',
            name='todate',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
