# Generated by Django 2.2 on 2020-05-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200418_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaredevelopment',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
