# Generated by Django 2.2 on 2020-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_softwaredevelopment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaredevelopment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
