# Generated by Django 2.2 on 2020-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200528_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearning',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='webdesigning',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
