# Generated by Django 2.2 on 2020-05-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200528_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinelearning',
            old_name='file',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='softwaredevelopment',
            old_name='file',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='webdesigning',
            old_name='file',
            new_name='video',
        ),
        migrations.AddField(
            model_name='machinelearning',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='softwaredevelopment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='webdesigning',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
