# Generated by Django 2.2 on 2020-05-28 08:28

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200528_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearning',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=website.models.get_upload_path, verbose_name=''),
        ),
    ]
