# Generated by Django 2.2 on 2020-05-28 08:37

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200528_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaredevelopment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='softwaredevelopment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=website.models.get_upload_path, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='webdesigning',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='webdesigning',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=website.models.get_upload_path, verbose_name=''),
        ),
    ]
