# Generated by Django 2.2 on 2020-05-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icon_color_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconcolortag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='iconcolortag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='taggedthing',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_color_tags_taggedthing_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedthing',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
    ]
