# Generated by Django 2.2 on 2020-03-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('project_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('project_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WebDesigning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('project_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
