# Generated by Django 2.2 on 2020-03-31 01:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icon_color_tags', '0001_initial'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdesigning',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='icon_color_tags.TaggedThing', to='icon_color_tags.IconColorTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='softwaredevelopment',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='icon_color_tags.TaggedThing', to='icon_color_tags.IconColorTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='machinelearning',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='icon_color_tags.TaggedThing', to='icon_color_tags.IconColorTag', verbose_name='Tags'),
        ),
    ]
