# Generated by Django 2.2 on 2020-03-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('details', models.CharField(blank=True, max_length=50)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
            ],
        ),
    ]
